FROM docker.elastic.co/elasticsearch/elasticsearch:9.2.4

RUN bin/elasticsearch-plugin install --batch \
    "https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.13-es9.2.4/ltr-plugin-v1.5.13-es9.2.4.zip"

